"""visitor: employee and visitor_record + seed employees

Revision ID: 4caea19d397c
Revises: ce50f0d6aab5
Create Date: 2026-05-07 15:26:16.091607+08:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '4caea19d397c'
down_revision: Union[str, Sequence[str], None] = 'ce50f0d6aab5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name_pinyin', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('nickname', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('department', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('dingtalk_user_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_department'), 'employee', ['department'], unique=False)
    op.create_index(op.f('ix_employee_is_active'), 'employee', ['is_active'], unique=False)
    op.create_index(op.f('ix_employee_name'), 'employee', ['name'], unique=False)
    op.create_index(op.f('ix_employee_name_pinyin'), 'employee', ['name_pinyin'], unique=False)
    op.create_table('visitor_record',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('company', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('purpose', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('host_employee_id', sa.Uuid(), nullable=True),
    sa.Column('host_name_snapshot', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('host_match_score', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('check_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('push_status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('push_error', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_record_created_at'), 'visitor_record', ['created_at'], unique=False)
    op.create_index(op.f('ix_visitor_record_host_employee_id'), 'visitor_record', ['host_employee_id'], unique=False)
    op.create_index(op.f('ix_visitor_record_status'), 'visitor_record', ['status'], unique=False)
    # ### end Alembic commands ###

    # === 员工通讯录种子（前端 mock 中出现的"被访人"姓名）===
    import uuid
    employee_table = sa.table(
        'employee',
        sa.column('id', sa.Uuid()),
        sa.column('name', sa.String()),
        sa.column('name_pinyin', sa.String()),
        sa.column('nickname', sa.String()),
        sa.column('department', sa.String()),
        sa.column('title', sa.String()),
        sa.column('phone', sa.String()),
        sa.column('dingtalk_user_id', sa.String()),
        sa.column('is_active', sa.Boolean()),
    )
    op.bulk_insert(employee_table, [
        {'id': uuid.uuid4(), 'name': '李明',   'name_pinyin': 'liming',   'nickname': '李经理',  'department': '技术部',  'title': '技术经理',  'phone': '13800000001', 'dingtalk_user_id': None, 'is_active': True},
        {'id': uuid.uuid4(), 'name': '张伟',   'name_pinyin': 'zhangwei', 'nickname': '张总监',  'department': '产品部',  'title': '产品总监',  'phone': '13800000002', 'dingtalk_user_id': None, 'is_active': True},
        {'id': uuid.uuid4(), 'name': '王芳',   'name_pinyin': 'wangfang', 'nickname': '王经理',  'department': '运营部',  'title': '运营经理',  'phone': '13800000003', 'dingtalk_user_id': None, 'is_active': True},
        {'id': uuid.uuid4(), 'name': '赵磊',   'name_pinyin': 'zhaolei',  'nickname': '赵总',    'department': '管理层',  'title': '副总裁',    'phone': '13800000004', 'dingtalk_user_id': None, 'is_active': True},
        {'id': uuid.uuid4(), 'name': '钱程',   'name_pinyin': 'qiancheng','nickname': '钱经理',  'department': '商务部',  'title': '商务经理',  'phone': '13800000005', 'dingtalk_user_id': None, 'is_active': True},
        {'id': uuid.uuid4(), 'name': '孙强',   'name_pinyin': 'sunqiang', 'nickname': '孙总监',  'department': '市场部',  'title': '市场总监',  'phone': '13800000006', 'dingtalk_user_id': None, 'is_active': True},
        {'id': uuid.uuid4(), 'name': '周莉',   'name_pinyin': 'zhouli',   'nickname': None,      'department': '设计部',  'title': '设计师',    'phone': '13800000007', 'dingtalk_user_id': None, 'is_active': True},
        {'id': uuid.uuid4(), 'name': '刘洋',   'name_pinyin': 'liuyang',  'nickname': None,      'department': '行政部',  'title': '行政专员',  'phone': '13800000008', 'dingtalk_user_id': None, 'is_active': True},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_record_status'), table_name='visitor_record')
    op.drop_index(op.f('ix_visitor_record_host_employee_id'), table_name='visitor_record')
    op.drop_index(op.f('ix_visitor_record_created_at'), table_name='visitor_record')
    op.drop_table('visitor_record')
    op.drop_index(op.f('ix_employee_name_pinyin'), table_name='employee')
    op.drop_index(op.f('ix_employee_name'), table_name='employee')
    op.drop_index(op.f('ix_employee_is_active'), table_name='employee')
    op.drop_index(op.f('ix_employee_department'), table_name='employee')
    op.drop_table('employee')
    # ### end Alembic commands ###
