"""document: template and draft tables

Revision ID: ce50f0d6aab5
Revises: a5b753a74244
Create Date: 2026-05-07 15:10:48.594862+08:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce50f0d6aab5'
down_revision: Union[str, Sequence[str], None] = 'a5b753a74244'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_template_is_system'), 'document_template', ['is_system'], unique=False)
    op.create_index(op.f('ix_document_template_type'), 'document_template', ['type'], unique=False)
    op.create_table('document_draft',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('topic', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('tone', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('audit_feedback', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['document_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_draft_passed'), 'document_draft', ['passed'], unique=False)
    op.create_index(op.f('ix_document_draft_type'), 'document_draft', ['type'], unique=False)
    op.create_index(op.f('ix_document_draft_user_id'), 'document_draft', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # === 内置模板 seed（4 类公文）===
    template_table = sa.table(
        'document_template',
        sa.column('id', sa.Uuid()),
        sa.column('type', sa.String()),
        sa.column('name', sa.String()),
        sa.column('description', sa.String()),
        sa.column('body', sa.String()),
        sa.column('is_system', sa.Boolean()),
    )
    import uuid
    seeds = [
        {
            'id': uuid.uuid4(), 'type': 'notice', 'name': '通用通知模板', 'is_system': True,
            'description': '适用于全员通知、安排通报等',
            'body': "# 关于{topic}的通知\n\n各部门：\n\n根据{keywords}相关要求，现就有关事项通知如下：\n\n一、\n二、\n三、\n\n请各部门认真组织落实。\n\n特此通知。\n\n[公司名称]\n[发文日期]",
        },
        {
            'id': uuid.uuid4(), 'type': 'request', 'name': '请示报告模板', 'is_system': True,
            'description': '适用于向上级请示决策、批准事项',
            'body': "# 关于{topic}的请示\n\n[上级单位]：\n\n关于{topic}事宜，结合{keywords}的实际情况，特向贵单位请示：\n\n一、背景情况\n二、拟办意见\n三、所需资源\n\n以上请示妥否，请批示。\n\n[申请部门]\n[日期]",
        },
        {
            'id': uuid.uuid4(), 'type': 'reward', 'name': '表彰决定模板', 'is_system': True,
            'description': '适用于先进个人/集体表彰',
            'body': "# 关于表彰{topic}的决定\n\n各部门、全体员工：\n\n为表彰{topic}所体现的{keywords}精神，经研究决定：\n\n一、给予表彰\n二、奖励内容\n三、希望全体员工以此为榜样\n\n[公司名称]\n[发文日期]",
        },
        {
            'id': uuid.uuid4(), 'type': 'meeting', 'name': '会议纪要模板', 'is_system': True,
            'description': '适用于会议纪要整理',
            'body': "# {topic}会议纪要\n\n**会议时间：**[年月日]\n**会议地点：**[地点]\n**主持人：**[姓名]\n**参会人员：**[列表]\n**记录人：**[姓名]\n\n## 一、会议议题\n围绕{keywords}展开讨论\n\n## 二、讨论要点\n\n## 三、决议事项\n\n## 四、后续行动",
        },
    ]
    op.bulk_insert(template_table, seeds)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_draft_user_id'), table_name='document_draft')
    op.drop_index(op.f('ix_document_draft_type'), table_name='document_draft')
    op.drop_index(op.f('ix_document_draft_passed'), table_name='document_draft')
    op.drop_table('document_draft')
    op.drop_index(op.f('ix_document_template_type'), table_name='document_template')
    op.drop_index(op.f('ix_document_template_is_system'), table_name='document_template')
    op.drop_table('document_template')
    # ### end Alembic commands ###
