"""policy: knowledge_file and policy_chunk

Revision ID: a5b753a74244
Revises: 793a7f0506cb
Create Date: 2026-05-07 14:26:04.893943+08:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5b753a74244'
down_revision: Union[str, Sequence[str], None] = '793a7f0506cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('knowledge_file',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('access_level', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_file_category'), 'knowledge_file', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_file_name'), 'knowledge_file', ['name'], unique=False)
    op.create_index(op.f('ix_knowledge_file_status'), 'knowledge_file', ['status'], unique=False)
    op.create_table('policy_chunk',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('embedding', Vector(2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['knowledge_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_policy_chunk_metadata_gin', 'policy_chunk', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_policy_chunk_file_id'), 'policy_chunk', ['file_id'], unique=False)
    # 注：embedding 维度 2048 超过 pgvector hnsw/ivfflat 的 2000 维上限。
    # MVP 阶段使用顺序扫描；后续若需 ANN，可切换到 halfvec(2048) + HNSW。
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_policy_chunk_file_id'), table_name='policy_chunk')
    op.drop_index('idx_policy_chunk_metadata_gin', table_name='policy_chunk', postgresql_using='gin')
    op.drop_table('policy_chunk')
    op.drop_index(op.f('ix_knowledge_file_status'), table_name='knowledge_file')
    op.drop_index(op.f('ix_knowledge_file_name'), table_name='knowledge_file')
    op.drop_index(op.f('ix_knowledge_file_category'), table_name='knowledge_file')
    op.drop_table('knowledge_file')
    # ### end Alembic commands ###
